// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantApp.API.Data;

#nullable disable

namespace RestaurantApp.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402171226_FixTableBranchRelation")]
    partial class FixTableBranchRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantApp.API.Modules.Audit.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewData")
                        .HasColumnType("jsonb")
                        .HasComment("Snapshot dữ liệu sau khi thay đổi");

                    b.Property<string>("OldData")
                        .HasColumnType("jsonb")
                        .HasComment("Snapshot dữ liệu trước khi thay đổi");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_audit_logs_created_at");

                    b.HasIndex("Module")
                        .HasDatabaseName("idx_audit_logs_module");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Auth.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Email đăng nhập");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Vai trò: Admin/Manager/Staff");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Tên đăng nhập");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Branch.Models.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Địa chỉ chi nhánh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Tên chi nhánh");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Số điện thoại chi nhánh");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_branches_restaurant_id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Customer.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer")
                        .HasComment("Điểm tích lũy hiện tại");

                    b.Property<string>("LoyaltyTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("bronze/silver/gold/platinum");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Phone")
                        .HasDatabaseName("idx_customers_restaurant_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Customer.Models.LoyaltyTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasComment("Điểm còn lại sau giao dịch");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointsChange")
                        .HasColumnType("integer")
                        .HasComment("Số điểm thay đổi (dương = cộng, âm = trừ)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_loyalty_transactions_customer_id");

                    b.ToTable("loyalty_transactions", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Employee.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("HiredAt")
                        .HasColumnType("date");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric(10,2)")
                        .HasComment("Lương theo giờ");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("owner/manager/cashier/waiter/chef/bartender");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("idx_employees_branch_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Employee.Models.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Giờ thực tế nhân viên kết thúc ca");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Giờ thực tế nhân viên vào ca (chấm công)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("scheduled/active/completed/absent");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("BranchId", "ShiftDate")
                        .HasDatabaseName("idx_shifts_branch_date");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giá nhập gần nhất");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("numeric(12,3)")
                        .HasComment("Số lượng tồn kho hiện tại");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("numeric(12,3)")
                        .HasComment("Mức cảnh báo tồn kho thấp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("idx_inventory_items_branch_id");

                    b.HasIndex("SupplierId");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityAfter")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("numeric(12,3)")
                        .HasComment("Số lượng thay đổi (dương = nhập, âm = xuất)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("import/export/adjust/waste");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("idx_inventory_transactions_item_id");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.MenuItemRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityUsed")
                        .HasColumnType("numeric(12,3)")
                        .HasComment("Lượng nguyên liệu mỗi suất");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("idx_recipes_menu_item_id");

                    b.ToTable("menu_item_recipes", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Tên nhà cung cấp");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_suppliers_restaurant_id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Danh mục đang được hiển thị hay ẩn");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("Thứ tự hiển thị danh mục trên menu");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_menu_categories_restaurant_id");

                    b.ToTable("menu_categories", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giá mặc định của món");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasComment("NULL = áp dụng cho tất cả chi nhánh");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasComment("FALSE khi món tạm hết hoặc không phục vụ");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_menu_items_category_id");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItemCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComboItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SingleItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComboItemId")
                        .HasDatabaseName("idx_menu_item_combos_combo_id");

                    b.HasIndex("SingleItemId")
                        .HasDatabaseName("idx_menu_item_combos_single_id");

                    b.ToTable("menu_item_combos", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("ExtraPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giá cộng thêm so với giá gốc của món");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OptionGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OptionGroupId");

                    b.ToTable("menu_item_options", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItemOptionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMultiple")
                        .HasColumnType("boolean")
                        .HasComment("TRUE = khách được chọn nhiều option cùng lúc");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasComment("TRUE = khách bắt buộc phải chọn");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("menu_item_option_groups", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Notification.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasComment("Đã đọc chưa");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("order_new/order_ready/inventory_low/reservation_new/payment_completed");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "IsRead")
                        .HasDatabaseName("idx_notifications_recipient_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.KitchenOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasComment("Số càng cao càng ưu tiên chế biến trước");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Thời điểm ticket xuất hiện ở bếp");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasComment("Snapshot số bàn để hiển thị nhanh trên KDS");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("BranchId", "Status")
                        .HasDatabaseName("idx_kitchen_orders_branch_status");

                    b.ToTable("kitchen_orders", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Số tiền được giảm");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("pending/preparing/ready/served/paid/cancelled");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Tổng tiền trước giảm giá");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Thuế VAT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Tổng tiền phải trả");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("idx_orders_branch_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_orders_created_at");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.HasIndex("TableId")
                        .HasDatabaseName("idx_orders_table_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentToKitchenAt")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Thời điểm nhân viên gửi món vào bếp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("pending/cooking/ready/served/cancelled");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Thành tiền");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giá tại thời điểm order, không thay đổi dù menu cập nhật sau");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.OrderItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExtraPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giá thêm snapshot tại thời điểm order");

                    b.Property<Guid>("MenuItemOptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("order_item_options", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.TableTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("ToTableId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Thời điểm chuyển bàn");

                    b.Property<Guid?>("TransferredBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("table_transfers", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Payment.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Số tiền thanh toán lần này");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Phương thức: cash/momo/zalopay/vnpay/credit_card...");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("text")
                        .HasComment("Mã giao dịch từ cổng thanh toán bên ngoài");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_payments_order_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Promotion.Models.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplyTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giá trị giảm");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giảm tối đa áp dụng với loại %");

                    b.Property<string>("MenuItemIds")
                        .HasColumnType("text");

                    b.Property<decimal>("MinOrderAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giá trị đơn hàng tối thiểu");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("percent_discount/fixed_discount/free_item/buy_x_get_y/loyalty_redeem");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Promotion.Models.VoucherCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer")
                        .HasComment("Số lần dùng tối đa (0 = unlimited)");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_vouchers_code");

                    b.HasIndex("PromotionId");

                    b.ToTable("voucher_codes", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Reservation.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("text");

                    b.Property<string>("GuestName")
                        .HasColumnType("text");

                    b.Property<string>("GuestPhone")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer")
                        .HasComment("Số lượng khách dự kiến");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Thời điểm khách muốn đến");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("pending/confirmed/seated/completed/cancelled/no_show");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("idx_reservations_branch_id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservedAt")
                        .HasDatabaseName("idx_reservations_reserved_at");

                    b.HasIndex("TableId");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Restaurant.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasComment("Đường dẫn logo nhà hàng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Tên nhà hàng");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasComment("ID chủ nhà hàng");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("TaxCode")
                        .HasColumnType("text")
                        .HasComment("Mã số thuế doanh nghiệp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Table.Models.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasComment("Sức chứa tối đa");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasComment("Tầng hoặc khu vực đặt bàn");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasComment("Mã QR để khách tự order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Trạng thái: available/occupied/reserved/cleaning");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasComment("Số bàn hiển thị");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("idx_tables_branch_id");

                    b.HasIndex("BranchId", "TableNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_tables_branch_number");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Branch.Models.Branch", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Restaurant.Models.Restaurant", "Restaurant")
                        .WithMany("Branches")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Customer.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Customer.Models.Customer", "Customer")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Employee.Models.Employee", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Branch.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Employee.Models.Shift", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Branch.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantApp.API.Modules.Employee.Models.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.InventoryItem", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Branch.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantApp.API.Modules.Inventory.Models.Supplier", "Supplier")
                        .WithMany("InventoryItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.InventoryTransaction", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Inventory.Models.InventoryItem", "InventoryItem")
                        .WithMany("Transactions")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.MenuItemRecipe", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Inventory.Models.InventoryItem", "InventoryItem")
                        .WithMany("Recipes")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.API.Modules.Menu.Models.MenuItem", null)
                        .WithMany("Recipes")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItem", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Menu.Models.MenuCategory", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItemCombo", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Menu.Models.MenuItem", "ComboItem")
                        .WithMany("ComboItems")
                        .HasForeignKey("ComboItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.API.Modules.Menu.Models.MenuItem", "SingleItem")
                        .WithMany()
                        .HasForeignKey("SingleItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComboItem");

                    b.Navigation("SingleItem");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItemOption", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Menu.Models.MenuItemOptionGroup", "OptionGroup")
                        .WithMany("Options")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionGroup");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItemOptionGroup", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Menu.Models.MenuItem", "MenuItem")
                        .WithMany("OptionGroups")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.KitchenOrder", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Order.Models.OrderItem", "OrderItem")
                        .WithOne("KitchenOrder")
                        .HasForeignKey("RestaurantApp.API.Modules.Order.Models.KitchenOrder", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.Order", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Branch.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantApp.API.Modules.Customer.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantApp.API.Modules.Table.Models.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Menu.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantApp.API.Modules.Order.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.OrderItemOption", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Order.Models.OrderItem", "OrderItem")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.TableTransfer", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Order.Models.Order", "Order")
                        .WithMany("TableTransfers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Payment.Models.Payment", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Order.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Promotion.Models.VoucherCode", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Promotion.Models.Promotion", "Promotion")
                        .WithMany("VoucherCodes")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Reservation.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Branch.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantApp.API.Modules.Customer.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantApp.API.Modules.Table.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Table.Models.Table", b =>
                {
                    b.HasOne("RestaurantApp.API.Modules.Branch.Models.Branch", "Branch")
                        .WithMany("Tables")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Branch.Models.Branch", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Customer.Models.Customer", b =>
                {
                    b.Navigation("LoyaltyTransactions");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Employee.Models.Employee", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.InventoryItem", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Inventory.Models.Supplier", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuCategory", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItem", b =>
                {
                    b.Navigation("ComboItems");

                    b.Navigation("OptionGroups");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Menu.Models.MenuItemOptionGroup", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("TableTransfers");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Order.Models.OrderItem", b =>
                {
                    b.Navigation("KitchenOrder");

                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Promotion.Models.Promotion", b =>
                {
                    b.Navigation("VoucherCodes");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Restaurant.Models.Restaurant", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("RestaurantApp.API.Modules.Table.Models.Table", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
